<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Vehiculo;
use App\Models\Dependencia;
use App\Models\EstadosVehiculo;
use App\Models\EstadosNafta;
use App\Models\Direcciones;

class VehiculoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Asegúrate de que existan estos registros en tu base de datos
        // Si no existen, crea primero los seeders para estas tablas

        $vehiculos = [
            [
                //*********************** seguridad ***************************************** */
                'dominio' => '',
                'marca' => 'Mercedez Benz',
                'modelo' => 'Sprinter',
                'unidad'=>'morguera',
                'anio' => 2000,
                'kilometros' =>0,
                'control_satelital' => true,
                'habilitado_prestamo' => false,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 59, // Ajusta según tu BD
                'id_direccion_actual' => 20,  // Ajusta según tu BD
                'id_estado_vehiculo' => 1,   // Disponible
                'id_estado_nafta' => 4,      // Lleno
            ],
            [
                'dominio' => 'AA 729 FH',
                'marca' => 'Renault',
                'modelo' => 'Clio Mio',
                'unidad'=> 'AR 672',
                'anio' => 2017,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(3),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1, //
                'id_estado_nafta' => 4,    //
            ],
            [
                'dominio' => 'AA 729 FJ',
                'marca' => 'Renault',
                'modelo' => 'Clio Mio',
                'unidad'=> 'AR 674',
                'anio' => 2017,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1, //
                'id_estado_nafta' => 4,    //
            ],
            [
                'dominio' => 'AA 729 FK',
                'marca' => 'Renault',
                'modelo' => 'Clio Blanco',
                'unidad'=> 'AR 675',
                'anio' => 2027,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => null,
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            [
                'dominio' => 'KAH 331',
                'marca' => 'Chevrolet',
                'modelo' => 'Corsa Blanco',
                'unidad'=> 'AS 554',
                'anio' => 2008,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
            [
                'dominio' => 'AA 047 CE',
                'marca' => 'Toyota',
                'modelo' => 'Etios Blanco',
                'unidad'=>'AS 626',
                'anio' => 2016,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                  'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
            [
                'dominio' => 'AE 389 AN',
                'marca' => 'Toyota',
                'modelo' => 'Etios Blanco',
                'unidad'=>'AS 822',
                'anio' => 2016,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
            [
                'dominio' => 'AG 656 FA',
                'marca' => 'Toyota',
                'modelo' => 'Yaris',
                'unidad'=>'AS 827',
                'anio' => 2021,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
  [
                'dominio' => 'AG 656 FB',
                'marca' => 'Toyota',
                'modelo' => 'Yaris',
                'unidad'=>'AS 828',
                'anio' => 2021,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                  'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

  [
                'dominio' => 'AG 656 FC',
                'marca' => 'Toyota',
                'modelo' => 'Yaris',
                'unidad'=>'AS 829',
                'anio' => 2021,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                   'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
  [
                'dominio' => 'AG 656 FD',
                'marca' => 'Toyota',
                'modelo' => 'Yaris',
                'unidad'=>'AS 830',
                'anio' => 2021,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                   'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
  [
                'dominio' => 'AG 656 FE',
                'marca' => 'Toyota',
                'modelo' => 'Yaris',
                'unidad'=>'AS 831',
                'anio' => 2021,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
                'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
              [
                'dominio' => 'AA 163 HN',
                'marca' => 'Citroen',
                'modelo' => 'Berlingo',
                'unidad'=>'P 628',
                'anio' => 2007,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
   [
                'dominio' => 'AF 123 YB',
                'marca' => 'Toyota',
                'modelo' => 'Hilux',
                'unidad'=>'P 755',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

       [
                'dominio' => 'AH 125 LH',
                'marca' => 'Nissan',
                'modelo' => 'Frontier',
                'unidad'=>'33556',
                'anio' => 2007,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

    [
                'dominio' => 'AF 253 OS',
                'marca' => 'Ford',
                'modelo' => 'Ranger',
                'unidad'=>' P 753',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

  [
                'dominio' => 'AF 123 XN',
                'marca' => 'Toyota',
                'modelo' => 'Hilux',
                'unidad'=>' P 754',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

         [
                'dominio' => 'OZZ 604',
                'marca' => 'Toyota',
                'modelo' => 'Hilux',
                'unidad'=>' P 803',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

              [
                'dominio' => 'sin dominio 0',
                'marca' => 'UTV',
                'modelo' => 'CAN - AM - VERDE',
                'unidad'=>'sin unidad 0',
                'anio' => 2000,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 67,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],





            //********************* transito ******************************************************

    [
                'dominio' => 'AA 163 HN',
                'marca' => 'Bajaj',
                'modelo' => 'Ranser 220F blanco y negro',
                'unidad'=>'MT 638',
                'anio' => 2012,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


  [
                'dominio' => 'A16 4MKD',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 negro',
                'unidad'=>'MT 131',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


  [
                'dominio' => 'A00 1VUK',
                'marca' => 'Bajaj',
                'modelo' => 'Ranser 220F blanco y negro',
                'unidad'=>'MT 636',
                'anio' => 2012,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


 [
                'dominio' => 'A00 1VUK',
                'marca' => 'Bajaj',
                'modelo' => 'Ranser 220F blanco y negro',
                'unidad'=>'MT 640',
                'anio' => 2012,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


 [
                'dominio' => 'A16 4MKA',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 725',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'A16 4MKE',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 726',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'A16 4MKI',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 726',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'A16 4MKH',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 727',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'A16 4MKG',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 728',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


 [
                'dominio' => 'A16 4MKF',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 729',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


 [
                'dominio' => 'A16 4MKC',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 732',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


 [
                'dominio' => 'A16 4MKB',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 733',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],



 [
                'dominio' => 'A15 7CSZ',
                'marca' => 'Bajaj',
                'modelo' => 'Rouser 200 Negro',
                'unidad'=>'MT 734',
                'anio' => 2013,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],


 [
                'dominio' => 'JVP 920',
                'marca' => 'Ford',
                'modelo' => 'Pick Up - Ranger',
                'unidad'=>'P 559',
                'anio' => 2011,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'MDO 097',
                'marca' => 'Renault',
                'modelo' => 'Clio',
                'unidad'=>'AS 708',
                'anio' => 2011,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'NPC 621',
                'marca' => 'Toyota',
                'modelo' => 'Hilux',
                'unidad'=>'P 614',
                'anio' => 2015,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 60,
                'id_direccion_actual' => 20,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

            /****************************** La primera ************************* */

           //
           //
           //
           //
           //
           /****************************** Delegacion Reta ********************* */
              [
                'dominio' => 'AA 628 LB',
                'marca' => 'Agrale',
                'modelo' => 'Camion Regador',
                'unidad'=>'',
                'anio' => 1993,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 13,
                'id_direccion_actual' => 6,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],
             [
                'dominio' => 'sin0dominio',
                'marca' => 'Volkswagen',
                'modelo' => 'sin modelo',
                'unidad'=>'C 658',
                'anio' => 1993,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 13,
                'id_direccion_actual' => 6,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

 [
                'dominio' => 'sin 00 dominio',
                'marca' => 'Iveco',
                'modelo' => 'C/Cabina',
                'unidad'=>'C 679',
                'anio' => 1993,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 13,
                'id_direccion_actual' => 6,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

             [
                'dominio' => 'sin 00 dominio',
                'marca' => 'Peugeot',
                'modelo' => 'Boxer Ambulancia',
                'unidad'=>'F 659',
                'anio' => 1993,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 13,
                'id_direccion_actual' => 6,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

             [
                'dominio' => 'sin dominio 0',
                'marca' => 'Iron XCMG',
                'modelo' => 'Pala Cargadora',
                'unidad'=>'sin unidad 0',
                'anio' => 1993,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 13,
                'id_direccion_actual' => 6,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

            /**************************************** planeamiento urbano *************************************** */
             [
                'dominio' => 'ADCZ 851',
                'marca' => 'Mercedez Benz',
                'modelo' => 'sin modelo',
                'unidad'=>'C 740',
                'anio' => 1993,
                'kilometros' => 0,
                'control_satelital' => true,
                'habilitado_prestamo' => true,
                'condiciones_prestamo' => '',
               'VTV' => now()->addMonths(6),
                'id_dependencia_duena' => 57,
                'id_direccion_actual' => 17,
                'id_estado_vehiculo' => 1,
                'id_estado_nafta' => 4,
            ],

            /***************************************** claromeco ********************************************** */




        ]
     ];

        foreach ($vehiculos as $vehiculo) {
            Vehiculo::create($vehiculo);
        }
    }
}
